In [2]:
import numpy as np

In [3]:
import sys

they are faster to use than a typical list
they use less bytes to store information by default = 4bytes
they store information at contigous memory locations so it becomes easier to read
when we are iterating through items there is no type checking as opposed to lists where there is type checking
SIMD VECTOR PROCESSING:- SINGLE INSTRUCTION MULTIPLE DATA
QUICKER CACHE UTILIXATION

In [4]:
#LISTS
a = [1,2,3]
b = [2,3,5]

print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
#multiplying corresponding numbers of arrays together
#we cannot do this in typical lists

a = np.array([1,3,5])
b = np.array([1,2,3])

a*b

array([ 1,  6, 15])

In [6]:
#initialize an array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[1,2,3],[1,2,3],[1,2,3]])  #similarly we can initialize a floating point 2d matrix
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
#Get dimension os ur array
a.ndim


1

In [11]:
b.ndim

2

In [12]:
#shape -> (rows,columns)
b.shape

(3, 3)

In [13]:
#memory it takes up
#type
a.dtype

dtype('int32')

In [14]:
c = np.array([3,4,5,6,], dtype='int16')

In [16]:
c.dtype
c.itemsize  #prints the number of bytes of memory it occupies

2

In [17]:
#get total size

c.size

4

In [20]:
#accessing changing specific rows,columns, elements etc

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [22]:
#get a specific element [r,c]

a[1,5]
a[1,-2]

13

In [29]:
# list1 = [1,2,3,4,5,6,7,8,9]
# print(list1[:-1])

#get a specific row in an array
# a[1,:]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#get a specific column
a[:,0]

array([1, 8])

In [40]:
print(a)
#getting elements with a two step
print(a[0,1:-1:2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[2 4 6]


In [43]:
print(a)
#changing a specific element
a[1,5] = 68

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [44]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 68 14]]


In [45]:
#changing a whole column

a[:,4] = 9

In [46]:
print(a)

[[ 1  2  3  4  9  6  7]
 [ 8  9 10 11  9 68 14]]


In [49]:
#intialize different types of arrays

#all zeroes matrix
# np.zeros(5)  #expects a shape to be passed into it
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
#all ones matrix
np.ones((1,2))

array([[1., 1.]])

In [51]:
#if we want to make a matrix which is full of a single number other than one and zeros above

# np.full(<shape>,<number>)
np.full((2,2),(89))

array([[89, 89],
       [89, 89]])

In [54]:
#random decimal numbers
np.random.rand(2,2,2)

array([[[0.68676468, 0.98590088],
        [0.54038448, 0.53428576]],

       [[0.69532696, 0.3322946 ],
        [0.61931496, 0.31245752]]])

In [56]:
#random integer values
np.random.randint(7, size = (3,3))  #generate a array of specificed shape but random values

array([[3, 6, 0],
       [2, 2, 0],
       [2, 3, 1]])

In [57]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#copying arrays
x = np.array([1,2,3])
y = x.copy()

In [61]:
y[0] = 99
print(y)
print(x)

[99  2  3]
[1 2 3]


In [64]:
#math operations

a = np.array([1,2,3,4,5])
# a+2
# a*2
a / 2  #performs element wise operations

array([0.5, 1. , 1.5, 2. , 2.5])

In [66]:
a = np.array([1,2,3,4,5])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [72]:
#linear algebra

a = np.full((2,3),1)
b = np.full((3,2),2)
print(a)
print(b)


print(f'after multiplying a and b {np.matmul(a,b)}')

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
after multiplying a and b [[6 6]
 [6 6]]


In [74]:
#to find the determinant of a matrix
# np.linalg.det()


b = np.array([[3,-4],[2,-5]])
np.linalg.det(b)

-7.000000000000001

In [76]:
#statistics
b = np.array([[3,-4],[2,-5]])
np.min(b)
np.max(b)

3